### ISSUE TITLE
File extension problem

### ISSUE THREAD

**Issue by viktorvi** [deanhume/html-minifier#25]
I have some javascript files which name include "aspx" string. 

For example: codes.aspx.js

html-minifier try to minify them becasure their name include "aspx". Minifier crash from these files.

**Comment by heldersepu** [comment]
This bug is caused by line 32:
https://github.com/deanhume/html-minifier/blob/master/ViewMinifier/Program.cs#L32

`if (filePath.ToLower().Contains(".cshtml") ||
 filePath.ToLower().Contains(".vbhtml") ||
 filePath.ToLower().Contains(".aspx") ||
 filePath.ToLower().Contains(".html") ||
 filePath.ToLower().Contains(".htm") ||
 filePath.ToLower().Contains(".ascx") ||
 filePath.ToLower().Contains(".master"))`

Not sure that should be using **Contains** maybe **EndsWith** is a better option

**Comment by deanhume** [comment]
Good spot @heldersepu

**Comment by deanhume** [comment]
This has been fixed and will be released with Release 1.8
