### ISSUE TITLE
var test = "1";// COMMENT

### ISSUE THREAD

**Issue by justlearntutors** [deanhume/html-minifier#50]
There is a bug for comments.

CSHTML FILE
@{
   decimal FirstPrice = 10;//priceList.PriceList.First(d => d.TotalSession == 1 && d.Duration == 60).Price;
}
<h1>1</h1>

RESULT
@{ decimal FirstPrice = 10;//priceList.PriceList.First(d => d.TotalSession == 1 && d.Duration == 60).Price; } <h1>1</h1>

// means all codes are comments and not included.

Can you fix?

**Comment by deanhume** [comment]
Closing this issue as it is not something that will likely be fixed. 

This is due to a number of reasons:

1. In order to truly 'minify' code, it shouldn't really include comments anyway
2. This is really tricky from a logic point of view - under what conditions do we keep / remove comments? (see the [following issue](https://github.com/deanhume/html-minifier/issues/34))

**Comment by justlearntutors** [comment]
@deanhume 
Thanks for the quick reply.

We will remove comments from cshtml.

**Comment by justlearntutors** [comment]
@deanhume 
How about using https://marketplace.visualstudio.com/items?itemName=MadsKristensen.CommentRemover ?
